#!/bin/bash

export ZENHOME=/usr/local/zenoss
export PYTHONPATH=/usr/local/zenoss/lib/python
export PATH=/usr/local/zenoss/bin:$PATH
export INSTANCE_HOME=$ZENHOME
export ZENPATH=/usr/local/zenoss/bin
export RRDCACHED=$ZENPATH/rrdcached

sudo -u zenoss -H -E $ZENPATH/zenoss $1

